# Generated by Django 2.2.12 on 2020-06-05 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('offense_description', models.TextField()),
                ('station_from', models.CharField(choices=[('CBD', 'CBD'), ('Kibera', 'Kibera'), ('Kangemi', 'Kangemi'), ('Kayole', 'Kayole'), ('Embakasi', 'Embakasi'), ('Buruburu', 'Buruburu'), ('Mathare', 'Mathare'), ('Rongai', 'Rongai')], default='CBD', max_length=50)),
                ('station_to', models.CharField(choices=[('CBD', 'CBD'), ('Kibera', 'Kibera'), ('Kangemi', 'Kangemi'), ('Kayole', 'Kayole'), ('Embakasi', 'Embakasi'), ('Buruburu', 'Buruburu'), ('Mathare', 'Mathare'), ('Rongai', 'Rongai')], default='CBD', max_length=50)),
                ('sacco_name', models.CharField(max_length=200)),
                ('occurrence_date', models.DateField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_report', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ushuhuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate', models.CharField(max_length=200)),
                ('sub_county', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contact', models.URLField(blank=True, max_length=128)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('cover', models.ImageField(default='images/blue-1.png', upload_to='images/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
